services:
  tfc-agent:
    build: .
    platform: linux/amd64
    container_name: tfc-agent
    restart: unless-stopped

    environment:
      TFC_AGENT_TOKEN: ${TFC_AGENT_TOKEN}
      TFC_AGENT_NAME: ${TFC_AGENT_NAME}

    volumes:
      - ${SSH_KEY_PATH}:/tmp/proxmox_automation:ro